name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus site
        run: npm run build
      
      - name: Configure Git author using secrets
        run: |
          git config --global user.name "${{ secrets.GH_CONFIG_NAME }}"
          git config --global user.email "${{ secrets.GH_CONFIG_EMAIL }}"


      - name: Deploy to GitHub Pages
        env:
          GIT_USER: ${{ secrets.USER }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          DEPLOYMENT_BRANCH: ${{secrets.DEPLOYMENT_BRANCH}}
        run: |
          npm run deploy